### ISSUE TITLE
Tests Currently Fail

### ISSUE THREAD

**Issue by bookercodes** [EvanHahn/lildash#202]
Running `npm test` results in the following error:

```
module.js:340
    throw err;
    ^

Error: Cannot find module '../../array/isEmpty'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/booker/Documents/Code/lildash/test/array/isEmpty.js:1:77)
```

I think this is just due to inconsistent naming. 

I am not sure which name you meant to use, so I'll leave it to you to correct.

**Comment by EvanHahn** [comment]
This should be fixed. Thanks for reporting!
